In [315]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [316]:
df = pd.read_csv("Amazon-Product-Reviews-Sentiment-Analysis.csv")

In [317]:
df.shape
df.head()
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Review     24999 non-null  object
 1   Sentiment  25000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 390.8+ KB

In [318]:
df["Sentiment"].nunique()

5

In [319]:
df = df.dropna()

In [320]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24999 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Review     24999 non-null  object
 1   Sentiment  24999 non-null  int64
dtypes: int64(1), object(1)
memory usage: 585.9+ KB

In [321]:
df

                                                  Review  Sentiment
0      Fast shipping but this product is very cheaply...          1
1      This case takes so long to ship and it's not e...          1
2      Good for not droids. Not good for iPhones. You...          1
3      The cable was not compatible between my macboo...          1
4      The case is nice but did not have a glow light...          1
...                                                  ...        ...
24995  These cables (lightning) are far superior to m...          5
24996  This unit performs exactly as advertised.  I u...          5
24997  I had the key cut at a local hardware store cu...          5
24998  I love my case I ordered from amazon. It wasn'...          5
24999  Awsome!!! I loved this little speaker. It has ...          5

[24999 rows x 2 columns]

In [322]:
df["Sentiment"] = df["Sentiment"].apply(lambda x:"positive" if x>3 else "negative")

In [323]:
# df["Sentiment"] = df["Sentiment"].apply(lambda x:"positive" if x>3 else("neutral" if x==3 else "negative"))

In [324]:
df.head()

                                              Review Sentiment
0  Fast shipping but this product is very cheaply...  negative
1  This case takes so long to ship and it's not e...  negative
2  Good for not droids. Not good for iPhones. You...  negative
3  The cable was not compatible between my macboo...  negative
4  The case is nice but did not have a glow light...  negative

In [325]:
# text Pre-processing
def clean_data(text):
    text = re.sub(r"<.*?>", "", text)                 
    text = re.sub(r"[^A-Za-z0-9\s]", "", text)       
    return text

df["Review"] = df["Review"].apply(clean_data)

In [326]:
df

                                                  Review Sentiment
0      Fast shipping but this product is very cheaply...  negative
1      This case takes so long to ship and its not ev...  negative
2      Good for not droids Not good for iPhones You c...  negative
3      The cable was not compatible between my macboo...  negative
4      The case is nice but did not have a glow light...  negative
...                                                  ...       ...
24995  These cables lightning are far superior to mos...  positive
24996  This unit performs exactly as advertised  I us...  positive
24997  I had the key cut at a local hardware store cu...  positive
24998  I love my case I ordered from amazon It wasnt ...  positive
24999  Awsome I loved this little speaker It has grea...  positive

[24999 rows x 2 columns]

In [327]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to C:\Users\suhasini
[nltk_data]     hegde\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\suhasini
[nltk_data]     hegde\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\suhasini
[nltk_data]     hegde\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [328]:
# Removing the stopWords and stemming
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

stop_words = set(stopwords.words("english"))  
ps = PorterStemmer()

def remove_stopwords_and_stem(text):
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
    stemmed_tokens = [ps.stem(word) for word in filtered_tokens]
    return " ".join(stemmed_tokens)

df["Review"] = df["Review"].apply(remove_stopwords_and_stem)

In [329]:

df

                                                  Review Sentiment
0      fast ship product cheapli made brought grandch...  negative
1                case take long ship even worth dont buy  negative
2      good droid good iphon use featur watch iphon w...  negative
3      cabl compat macbook iphon also connector came ...  negative
4      case nice glow light im disappoint product did...  negative
...                                                  ...       ...
24995  cabl lightn far superior cabl market even appl...  positive
24996  unit perform exactli advertis use climb mounta...  positive
24997  key cut local hardwar store cut free program u...  positive
24998  love case order amazon wasnt color look onlin ...  positive
24999  awsom love littl speaker great sound super cut...  positive

[24999 rows x 2 columns]

In [330]:
y= df['Sentiment']

In [331]:
y

0        negative
1        negative
2        negative
3        negative
4        negative
           ...
24995    positive
24996    positive
24997    positive
24998    positive
24999    positive
Name: Sentiment, Length: 24999, dtype: object

In [332]:
y[y == 'positive' ] #9999
y[y == 'negative' ] #10,000
# y[y == 'neutral' ] #5000

0        negative
1        negative
2        negative
3        negative
4        negative
           ...
14995    negative
14996    negative
14997    negative
14998    negative
14999    negative
Name: Sentiment, Length: 15000, dtype: object

In [336]:
# Vectorization, Train test Spilt, model selection
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(df['Review'])

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=.25, random_state=42)

# LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)

# SVC
# model = SVC(kernel='linear')
# model.fit(X_train, y_train)
# y_predict = model.predict(X_test)

In [337]:
# # Train test Spilt, Vectorization, # model Seldction
# X = df['Review']

# X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=.25, random_state=42)

# from sklearn.feature_extraction.text import TfidfVectorizer
# tf = TfidfVectorizer(max_features=5000)

# X_train_vec = tf.fit_transform(X_train)
# X_test_vec = tf.transform(X_test)

# # model Seldction
# model = LogisticRegression()
# model.fit(X_train_vec, y_train)
# y_predict = model.predict(X_test_vec)

In [338]:
# Evaluation metrics
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))
print("accuracy_score:", round(accuracy_score(y_test, y_predict)*100, 4))

              precision    recall  f1-score   support

    negative       0.81      0.88      0.85      3718
    positive       0.80      0.70      0.75      2532

    accuracy                           0.81      6250
   macro avg       0.81      0.79      0.80      6250
weighted avg       0.81      0.81      0.81      6250

accuracy_score: 80.816

In [339]:
import joblib
joblib.dump(model, 'sentiment_model.pkl')
joblib.dump(tf, 'tfidf_vectorizer.pkl')

['tfidf_vectorizer.pkl']